#!/usr/bin/env bash
#
# Rewrite reference/outstanding-commits.md from the current state of the repo.
#
# The table is generated, never hand-edited. Anything already reflected in
# ornl-next, and anything from before the last full release, is left out.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECK="${HERE}/check-paths.sh"
OUT="${HERE}/../reference/outstanding-commits.md"

# Passed straight through to check-paths.sh, which owns remote resolution.
CHECK_ARGS=()

usage() {
    cat <<'USAGE'
Usage: regenerate-outstanding.sh [--remote NAME] [--main REF] [--ornl REF] [--out FILE]

  --remote NAME  git remote holding mantidproject/mantid (default: auto-detect)
  --main REF     full ref for upstream main
  --ornl REF     full ref for the ornl-next work
  --out FILE     where to write (default: ../reference/outstanding-commits.md)
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --remote|--main|--ornl) CHECK_ARGS+=("$1" "$2"); shift 2 ;;
        --out) OUT="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
    esac
done

cd "$(git rev-parse --show-toplevel)"

release="$(git tag --list 'v*' --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -1)"
today="$(date +%Y-%m-%d)"

in_sync=0
differing="$("$CHECK" "${CHECK_ARGS[@]+"${CHECK_ARGS[@]}"}")" || in_sync=1

# The header line names the refs check-paths.sh actually resolved, so the
# generated file records what was compared rather than what was requested.
refs_line="$(printf '%s\n' "$differing" | head -1)"
main_ref="$(sed -n 's/.*between .* and \(.*\)\.$/\1/p; s/^Configuration files on \(.*\) not yet.*$/\1/p' <<<"$refs_line" | head -1)"
ornl_ref="$(sed -n 's/^In sync: .* between \(.*\) and .*\.$/\1/p; s/.*not yet reflected in \(.*\):$/\1/p' <<<"$refs_line" | head -1)"

{
    echo "# Outstanding ornl-next configuration commits"
    echo
    echo "Generated by \`scripts/regenerate-outstanding.sh\` on ${today}. Do not hand-edit."
    echo
    echo "| | |"
    echo "|---|---|"
    echo "| baseline release | \`${release}\` |"
    echo "| main ref | \`${main_ref}\` (\`$(git rev-parse --short "$main_ref")\`) |"
    echo "| ornl-next ref | \`${ornl_ref}\` (\`$(git rev-parse --short "$ornl_ref")\`) |"
    echo

    if [[ $in_sync -eq 0 ]]; then
        echo "## Status: in sync"
        echo
        echo "No configuration paths differ between \`${ornl_ref}\` and \`${main_ref}\`."
        echo "There is nothing to cherry-pick."
    else
        echo "## Status: out of sync"
        echo
        echo "### Differing files"
        echo
        printf '%s\n' "$differing" | tail -n +2 | sed 's/^/- `/; s/$/`/'
        echo
        echo "### Commits to consider, oldest first"
        echo
        echo "Cherry-pick in the order listed. Confirm each one is genuinely absent"
        echo "by content -- ancestry is not a reliable test, see SKILL.md."
        echo
        echo "| commit | date | message |"
        echo "|--------|------|---------|"
        "$CHECK" "${CHECK_ARGS[@]+"${CHECK_ARGS[@]}"}" --log --since "$release" 2>/dev/null \
            | while read -r sha date msg; do
                printf '| `%s` | %s | %s |\n' "$sha" "$date" "${msg//|/\\|}"
            done
    fi
} > "$OUT"

echo "wrote ${OUT}"
