#!/usr/bin/env bash
#
# Rewrite reference/outstanding-commits.md from the current state of the repo.
#
# The table is generated, never hand-edited. Anything already reflected in
# ornl-next, and anything from before the last full release, is left out.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECK="${HERE}/check-paths.sh"
OUT="${HERE}/../reference/outstanding-commits.md"

MAIN_REF="upstream/main"
ORNL_REF="upstream/ornl-next"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --main) MAIN_REF="$2"; shift 2 ;;
        --ornl) ORNL_REF="$2"; shift 2 ;;
        --out)  OUT="$2"; shift 2 ;;
        -h|--help)
            echo "Usage: regenerate-outstanding.sh [--main REF] [--ornl REF] [--out FILE]"
            exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done

cd "$(git rev-parse --show-toplevel)"

release="$(git tag --list 'v*' --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -1)"
today="$(date +%Y-%m-%d)"
main_sha="$(git rev-parse --short "$MAIN_REF")"
ornl_sha="$(git rev-parse --short "$ORNL_REF")"

in_sync=0
differing="$("$CHECK" --main "$MAIN_REF" --ornl "$ORNL_REF")" || in_sync=1

{
    echo "# Outstanding ornl-next configuration commits"
    echo
    echo "Generated by \`scripts/regenerate-outstanding.sh\` on ${today}. Do not hand-edit."
    echo
    echo "| | |"
    echo "|---|---|"
    echo "| baseline release | \`${release}\` |"
    echo "| \`${MAIN_REF}\` | \`${main_sha}\` |"
    echo "| \`${ORNL_REF}\` | \`${ornl_sha}\` |"
    echo

    if [[ $in_sync -eq 0 ]]; then
        echo "## Status: in sync"
        echo
        echo "No configuration paths differ between \`${ORNL_REF}\` and \`${MAIN_REF}\`."
        echo "There is nothing to cherry-pick."
    else
        echo "## Status: out of sync"
        echo
        echo "### Differing files"
        echo
        printf '%s\n' "$differing" | tail -n +2 | sed 's/^/- `/; s/$/`/'
        echo
        echo "### Commits to consider, oldest first"
        echo
        echo "Cherry-pick in the order listed. Confirm each one is genuinely absent"
        echo "by content -- ancestry is not a reliable test, see SKILL.md."
        echo
        echo "| commit | date | message |"
        echo "|--------|------|---------|"
        "$CHECK" --main "$MAIN_REF" --ornl "$ORNL_REF" --log --since "$release" 2>/dev/null \
            | while read -r sha date msg; do
                printf '| `%s` | %s | %s |\n' "$sha" "$date" "${msg//|/\\|}"
            done
    fi
} > "$OUT"

echo "wrote ${OUT}"
