#!/usr/bin/env bash
#
# Rewrite references/outstanding-commits.md from the current state of the repo.
#
# The table is generated, never hand-edited. Anything already reflected in
# ornl-next, and anything from before the last full release, is left out.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECK="${HERE}/check-paths.sh"
OUT="${HERE}/../references/outstanding-commits.md"

# Passed straight through to check-paths.sh, which owns remote resolution.
CHECK_ARGS=()

# Explicitly requested commits. These reach the commit table but deliberately
# not the file diff: they are work to do on their own terms, not evidence that
# a configuration path differs.
INCLUDE_ARGS=()
INCLUDE_SHAS=()

usage() {
    cat <<'USAGE'
Usage: regenerate-outstanding.sh [--remote NAME] [--main REF] [--ornl REF]
                                 [--include SHA] [--out FILE]

  --remote NAME  git remote holding mantidproject/mantid (default: auto-detect)
  --main REF     full ref for upstream main
  --ornl REF     full ref for the ornl-next work
  --include SHA  commit to record as work to do whether or not it touches a
                 configuration path. Repeatable, and accepts a comma-separated
                 list.
  --out FILE     where to write (default: ../references/outstanding-commits.md)
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --remote|--main|--ornl) CHECK_ARGS+=("$1" "$2"); shift 2 ;;
        --include)
            IFS=',' read -r -a _inc <<< "$2"
            for _sha in "${_inc[@]}"; do
                [[ -n "$_sha" ]] || continue
                INCLUDE_ARGS+=(--include "$_sha")
                INCLUDE_SHAS+=("$_sha")
            done
            shift 2 ;;
        --out) OUT="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
    esac
done

cd "$(git rev-parse --show-toplevel)"

release="$(git tag --list 'v*' --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -1)"
today="$(date +%Y-%m-%d)"

in_sync=0
differing="$("$CHECK" "${CHECK_ARGS[@]+"${CHECK_ARGS[@]}"}")" || in_sync=1

# The header line names the refs check-paths.sh actually resolved, so the
# generated file records what was compared rather than what was requested.
refs_line="$(printf '%s\n' "$differing" | head -1)"
main_ref="$(sed -n 's/.*between .* and \(.*\)\.$/\1/p; s/^Configuration files on \(.*\) not yet.*$/\1/p' <<<"$refs_line" | head -1)"
ornl_ref="$(sed -n 's/^In sync: .* between \(.*\) and .*\.$/\1/p; s/.*not yet reflected in \(.*\):$/\1/p' <<<"$refs_line" | head -1)"

{
    echo "# Outstanding ornl-next configuration commits"
    echo
    echo "Generated by \`scripts/regenerate-outstanding.sh\` on ${today}. Do not hand-edit."
    echo
    echo "| | |"
    echo "|---|---|"
    echo "| baseline release | \`${release}\` |"
    echo "| main ref | \`${main_ref}\` (\`$(git rev-parse --short "$main_ref")\`) |"
    echo "| ornl-next ref | \`${ornl_ref}\` (\`$(git rev-parse --short "$ornl_ref")\`) |"
    echo

    if [[ $in_sync -eq 0 && ${#INCLUDE_SHAS[@]} -eq 0 ]]; then
        echo "## Status: in sync"
        echo
        echo "No configuration paths differ between \`${ornl_ref}\` and \`${main_ref}\`."
        echo "There is nothing to cherry-pick."
    else
        echo "## Status: out of sync"
        echo
        echo "### Differing files"
        echo
        if [[ $in_sync -eq 0 ]]; then
            echo "None. The commits below were requested explicitly."
        else
            printf '%s\n' "$differing" | tail -n +2 | sed 's/^/- `/; s/$/`/'
        fi
        echo
        echo "### Commits to consider, oldest first"
        echo
        echo "Cherry-pick in the order listed. Confirm each one is genuinely absent"
        echo "by content -- ancestry is not a reliable test, see SKILL.md."
        if [[ ${#INCLUDE_SHAS[@]} -gt 0 ]]; then
            joined=""
            for _sha in "${INCLUDE_SHAS[@]}"; do
                joined+=", \`$(git rev-parse --short "$_sha" 2>/dev/null || echo "$_sha")\`"
            done
            echo
            echo "Requested explicitly: ${joined#, }. These are listed whether or"
            echo "not they touch a configuration path, merged into the table in"
            echo "topological order."
        fi
        echo
        echo "| commit | date | message |"
        echo "|--------|------|---------|"
        "$CHECK" "${CHECK_ARGS[@]+"${CHECK_ARGS[@]}"}" \
                 "${INCLUDE_ARGS[@]+"${INCLUDE_ARGS[@]}"}" \
                 --log --since "$release" 2>/dev/null \
            | while read -r sha date msg; do
                printf '| `%s` | %s | %s |\n' "$sha" "$date" "${msg//|/\\|}"
            done
    fi
} > "$OUT"

echo "wrote ${OUT}"
